# run autoencoder on IARPA sentences
model: /om/user/jennhu/OpenNMT-py/models/news/news-model_step_100000.pt
src: /om/user/jennhu/anti-sentences/annotation/features/keys/key_384sentences_dereferencedpronouns.txt
output: data/news/pred_384sentences_dereferencedpronouns.txt
replace_unk: verbose
