# run autoencoder on 5 example sentences for testing/debugging
model: /om/user/jennhu/OpenNMT-py/models/news_step_100000.pt
src: /om/user/jennhu/OpenNMT-py/data/news/debug.txt
output: data/news/preds/pred-debug.txt

# share source and target vocabulary
share_vocab: true

# translate one sentence at a time
batch_size: 1

# intervention flags
flip_type: sign
flip_target: network
flip_size: 25

# logging
report_bleu: true
report_time: true
